services:
  - type: web
    name: ymg-landing-page
    env: static
    buildCommand: npm run build
    publish: dist
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
